src/services/aws/tests.rs
src/services/aws/v4.rs

fix: Fix aws sigv4 not correct for s3 GetObject

---

Cargo.toml
benches/aws.rs
src/request.rs
src/services/aws/v4.rs

feat: Add benchmarks for the further improving

---

.taplo.toml
Cargo.toml
src/services/aws/loader.rs

feat: Implement test for aws env loader

---

src/services/aws/loader.rs
testdata/services/aws/default_config
testdata/services/aws/default_credential

test: Implement unit tests for region and profile

---

src/services/aws/constants.rs
src/services/aws/loader.rs
src/time.rs

test: Implement WebIdentityTokenLoader test

---

src/services/aws/loader.rs
src/services/aws/v4.rs

feat: Implement default load chain for credential and region

---

Cargo.toml
src/request.rs
src/services/aws/loader.rs
src/services/aws/v4.rs
src/time.rs

fix: ListObjects not supported correctly

---

src/request.rs
src/services/aws/v4.rs

fix: Port in url not added into CanonicalRequest

---

CHANGELOG.md
LICENSE
rust-toolchain.toml

Bump to version 0.0.1

---

Cargo.toml

deps: reqsign needs time >= 0.3.6 to build

---

CHANGELOG.md
Cargo.toml

Bump to version 0.0.2

---

tests/azure/storage.rs

test: Add more list test cases for azblob

---

src/services/aws/constants.rs
src/services/aws/v4.rs
tests/aws/v4.rs

fix(service/aws/v4): Request path should be encoded by UriEncode

---

CHANGELOG.md
Cargo.toml

Bump to version 0.0.3

---

README.md
src/services/aws/loader.rs
src/services/aws/v4.rs

refactor(services/aws): Load region in blocking

---

Cargo.toml
benches/aws.rs
src/lib.rs
src/request.rs
src/services/aws/loader.rs
src/services/aws/v4.rs
tests/aws/v4.rs

refactor(services/aws): Load cred in blocking

---

src/services/azure/loader.rs
src/services/azure/storage.rs
tests/azure/storage.rs

refactor(services/azure): Make azure sign with block

---

Cargo.toml
src/request.rs
src/services/google/signer.rs
tests/google/storage.rs

refactor(services/google): Make google singer is blocking

---

.env.example
.github/workflows/ci.yml
.github/workflows/docs.yaml
Cargo.toml
src/services/aws/loader.rs
src/services/aws/mod.rs
testdata/services/aws/.gitignore
tests/aws/v4.rs

feat(aws/v4): Add test for WebIdentityTokenLoader

---

src/services/aws/loader.rs

Fix https://github.com/datafuselabs/opendal/issues/288

fix(services/aws): Increase retry times for AWS STS

---

src/services/aws/loader.rs

feat(services/s3): Make sure token file has been re-read

---

Cargo.toml

Bump to version 0.0.5

---

src/services/aws/loader.rs

feat(aws): Add dummy loader

---

src/lib.rs
src/services/aws/loader.rs
src/services/aws/v4.rs
src/services/azure/storage.rs
src/services/google/signer.rs
src/time.rs

docs: Make sure all our public APIs have docs

---

.github/workflows/ci.yml
.github/workflows/docs.yaml
Cargo.toml
benches/aws.rs
src/lib.rs
src/request.rs
tests/azure/storage.rs
tests/google/storage.rs

feat: Enable feature gates

---

.github/workflows/ci.yml
src/services/aws/mod.rs
src/services/aws/v4.rs
tests/aws/v4.rs

fix(services/aws/v4): Percent encoded URI not handled correctly

---

tests/azure/storage.rs

feat(azure): Add test for azure storage

---

src/lib.rs

Fix https://github.com/Xuanwo/reqsign/issues/96

refactor: Make SignableRequest private

---

src/services/aws/v4.rs

Fix https://github.com/Xuanwo/reqsign/issues/91

feat: Add tests for query sign with token

---

src/services/aws/v4.rs

Fix https://github.com/Xuanwo/reqsign/issues/94

fix: Fix query signing for aws v4 with sse headers

---

Cargo.toml

Bump to version v0.3

---

Cargo.toml
README.md
src/hash.rs
src/lib.rs
src/services/huaweicloud/constants.rs
src/services/huaweicloud/credential.rs
src/services/huaweicloud/loader.rs
src/services/huaweicloud/mod.rs
src/services/huaweicloud/obs.rs
src/services/mod.rs

Hi! I have implemented the Huawei Cloud Signer, and test it locally, PTAL.
I'm not sure how to write integration tests for the new signer, and where to store ak / sk for test.

feat(services): Implement huaweicloud obs signer

---

Cargo.toml
src/services/huaweicloud/obs.rs

Bump to version 0.4.0

---

Cargo.toml
README.md

Bump to version 0.4.1

---

Cargo.toml
src/services/aws/loader.rs
src/services/google/signer.rs
tests/aws/v4.rs
tests/azure/storage.rs
tests/google/storage.rs

refator: Use ureq for blocking requests

---

Cargo.toml

deps: Bump backon to 0.1

---

Cargo.toml

Bump to version 0.4.2

---

src/services/aws/v4.rs

Signed-off-by: ClSlaid <cailue@bupt.edu.cn>

feat: expose security-token to users

---

Cargo.toml

Bump to version 0.4.3

---

Cargo.toml

Bump to version 0.5.0

---

src/services/aliyun/oss.rs
tests/aliyun/oss.rs
tests/aws/v4.rs

fix: Aliyun OSS SignatureDoesNotMatch for special chars

---

Cargo.toml
README.md
src/lib.rs

Bump to version 0.5.1

---

Cargo.toml

Bump to version 0.5.2

---

src/lib.rs
src/services/huaweicloud/obs.rs
src/time.rs

refactor: Cleanup exported types

---

README.md
src/aws/config.rs
src/aws/credential.rs
src/aws/v4.rs
src/azure/storage/credential.rs
src/azure/storage/signer.rs
src/huaweicloud/obs/credential.rs

Fix https://github.com/Xuanwo/reqsign/issues/144

feat: Add assume role support for AWS

---

Cargo.toml

Bump to version 0.6.0

---

Cargo.toml

Bump to version 0.6.1

---

src/aliyun/credential.rs
src/aws/credential.rs

Fix https://github.com/Xuanwo/reqsign/issues/159

fix: Retry in the outer loop instead of every loader

---

Cargo.toml

Bump to version 0.6.2

---

Cargo.toml

Bump to version 0.6.3

---

Cargo.toml

Bump to version 0.6.4

---

src/aws/config.rs
src/aws/constants.rs
src/aws/credential.rs

Fix https://github.com/Xuanwo/reqsign/issues/170

feat(services/aws): Add regional sts support

---

Cargo.toml

Bump to version 0.6.5

---

src/aws/credential.rs

fix(aws): assume_role_with_web_identity should also use endpoint

---

Cargo.toml

Bump to version 0.6.6

---

src/aws/credential.rs

Fix https://github.com/Xuanwo/reqsign/issues/169

feat(services/aws): Implement IMDSv2 support

---

src/aliyun/oss.rs
tests/aliyun/oss.rs

feat: Implement query sign for oss

---

Cargo.toml

Bump version 0.6.7

---

src/aws/credential.rs
src/aws/v4.rs

feat(aws): Allow disable load from imds v2

---

Cargo.toml

Bump to version 0.6.9

---

src/aws/credential.rs

feat(aws): Re-order credential loader

---

Cargo.toml

Bump to version 0.7.1

---

src/google/credential.rs
src/google/mod.rs
src/google/signer.rs
src/lib.rs

feat: Implement token loader for google

---

README.md

docs: Fix build status link

---

Cargo.toml

Bump to version 0.7.2

---

src/google/credential.rs

feat: Add Send & Sync bound for TokenLoad

---

Cargo.toml

Bump to version 0.7.3

---

Cargo.toml

feat: Enable rustls support

---

Cargo.toml

Bump to version 0.7.4

---

src/aliyun/credential.rs
src/aliyun/oss.rs

fix(aliyun): Fix query sign with security token

---

Cargo.toml

Bump to version 0.7.6

---

.github/workflows/ci.yml
benches/aws.rs
examples/google_adc.rs
rustfmt.toml
src/aliyun/credential.rs
src/aws/config.rs
src/aws/credential.rs
src/aws/mod.rs
src/aws/region.rs
src/aws/v4.rs
src/google/credential.rs
src/google/signer.rs
src/lib.rs
tests/aws/v4.rs

refactor(aws): Allow users to control the loader logic

---

src/aws/credential.rs

feat(aws): Allow specify the client for sending http requests

---

Cargo.toml

Bump to version 0.8

---

src/aws/credential.rs
src/lib.rs

feat: Export AwsCredentialLoad

---

Cargo.toml

Bump to version 0.8.1

---

src/aliyun/credential.rs

fix(tests): Don't panic if test env not setup

---

src/aws/credential.rs
src/aws/region.rs

The two functions do exactly the same?

remove aws config loading duplication

---

Cargo.toml
src/aliyun/credential.rs
src/aws/credential.rs
src/google/credential.rs

deps: Bump backon to v0.4

---

Cargo.toml

Bump to version 0.8.2

---

src/azure/storage/signer.rs

feat(azblob): support signing without `x-ms-version`

---

src/tencent/credential.rs

feat: Add debug log if cos web_identity is misconfigured

---

Cargo.toml

This reverts commit 648c950f16123dd8937b8c3707f19cf59fb06766.

Revert "chore(deps): Update jsonwebtoken requirement from 8 to 9 (#369)"

---

src/aws/credential.rs

fix: fix `AWS_EC2_METADATA_DISABLED` logic error

---

Cargo.toml
src/lib.rs
src/oracle/config.rs
src/oracle/constants.rs
src/oracle/credential.rs
src/oracle/mod.rs
src/oracle/oci.rs

only for requests without body currently

feat(oci): init oci api key sign support

---

src/aws/config.rs

Fix for #413
Added extra test to verify profile prefix is added

AWS Profile loading code looks for wrong key in config #413

---

README.md
src/aws/credential.rs
src/aws/v4.rs
src/azure/storage/signer.rs
src/google/signer.rs
src/huaweicloud/obs/signer.rs
src/lib.rs

sorry i did not recognize that the readme is also needed to be modified in #463
if there're other docs need to be modified together, please let me know

fix: readme about signing Parts instead of Request

---

src/aws/config.rs
src/aws/credential.rs

**Changes Done**
Add support for configuring session tags during assume role operation
Fixes https://github.com/Xuanwo/reqsign/issues/467

Add support for assume role session tags

---

services/aliyun-oss/src/signer.rs

Will fix https://github.com/apache/opendal/issues/5391

Percent encoding query params for aliyun OSS

---

Cargo.toml
services/aws-v4/src/provide_credential/assume_role.rs

chore: upgrade and tidy dependencies

---

.env.example
.github/1password-setup.md
.github/workflows/aws_v4.yml
services/aws-v4/tests/credential_providers/mod.rs
services/aws-v4/tests/credential_providers/s3_express.rs

Close https://github.com/Xuanwo/reqsign/issues/594

feat(services/aws-v4): Add test for s3 express session

---

core/src/api.rs
services/aliyun-oss/src/provide_credential/default.rs
services/aws-v4/src/provide_credential/default.rs
services/azure-storage/src/provide_credential/default.rs
services/google/src/provide_credential/default.rs
services/huaweicloud-obs/src/provide_credential/default.rs
services/oracle/src/provide_credential/default.rs
services/tencent-cos/src/provide_credential/default.rs

Close https://github.com/Xuanwo/reqsign/issues/614
---
**This PR was primarily authored with Claude Code using Opus 4.1 and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.**

feat: Add push_front for all default credential providers

---

.github/1password-setup.md
.github/workflows/aws_v4.yml
.github/workflows/azure_storage.yml
.github/workflows/google.yml

Modified according to [ASF approved_patterns](https://github.com/apache/infrastructure-actions/blob/f5f890cfb87993bb34ae40558f4895ea985c8f31/approved_patterns.yml).

ci: Update GitHub Action to ASF approved patterns

---

.asf.yaml

Added configuration for GitHub integration and notifications.

chore: add .asf.yaml file
