apache/opendal-reqsign

Cargo.toml, src/services/aws/loader.rs, tests/aws/v4.rs
=> feat(aws): Retry while meeting errors

Cargo.toml, src/services/google/signer.rs
=> chore: Remove reference to reqwest::blocking

src/services/huaweicloud/mod.rs, src/services/huaweicloud/obs.rs, src/services/huaweicloud/subresource.rs
https://support.huaweicloud.com/intl/en-us/api-obs/obs_04_0010.html
In OBS, we can only add specific subresource params in the CanonicalizedResource, and other params should be discarded.
e.g. For a list object request:
> GET /?delimiter=/
The CanonicalizedResource is `/bucket/`, not `/bucket/?delimiter=/`, since `delimiter` is not a subresource.
=> feat: Filt subresource in obs signer

Cargo.toml, src/google/signer.rs
Avoid pulling `rustls`.
Prerequisite for https://github.com/datafuselabs/opendal/issues/812
=> refactor: disable default features for `ureq`

src/aws/credential.rs
=> fix(aws): x-aws-ec2-metadata-token-ttl-second not set & parse json

src/aliyun/credential.rs, src/aws/credential.rs, src/aws/v4.rs, src/azure/storage/signer.rs, src/credential.rs
Right now the only auth system supported for Azure Blobs is Shared Key, which is not recommended. Shared Access Signatures are better and provide more fine-grained account control.
=> Add support for creating an azure credential with a SAS token

Cargo.toml, src/google/constants.rs, src/google/credential.rs, src/google/mod.rs, src/google/signer.rs, src/google/v4.rs, testdata/services/google/testbucket_credential.json
I've started again from scratch, duplicating everything I needed for google v4 signing. 
There is a "second" builder now, and I am not sure if we want to keep that or not. 
I left in the header signing method, but I can remove it if you don't want it for now.
I believe we could just as well replace the current Google implementation with this one, I am not aware of any drawbacks and it would get rid of the more complicated token procedure.
Still need to add some tests.
=> feat: Add sign_query support for google

src/azure/storage/credential.rs, src/azure/storage/signer.rs
This PR is to add AAD OAuth support for Azure Storage. Since AAD OAuth essentially authorizes through Access Tokens, we directly added a BearerToken in the Credential.
Please note that we have not implemented how to obtain the Access Token, and this part needs to be implemented by the user themselves.
close #164  ?
maybe we can use https://github.com/Azure/login action to test this changes in the feature.
=> 🦙 Azure Storage Add AAD OAuth support

Cargo.toml, src/azure/storage/config.rs, src/azure/storage/imds_credential.rs, src/azure/storage/loader.rs, src/azure/storage/mod.rs, src/azure/storage/signer.rs, tests/azure/storage.rs
This is part of #322. We added Azure IMDS support according to this [document](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http), but since IMDS authentication needs to be tested on an Azure VM, we may not be able to test it on CI. Below are my local testing methods.
- Create a new VM on Azure
- Enable Identity
- Clone this repository on VM.
- Set .env variable
```
REQSIGN_AZURE_STORAGE_TEST=on
REQSIGN_AZURE_STORAGE_CRED=imds
```
- Run test
From the test results, I think everything is OK. PTAL @Xuanwo
=> 🍋 feat: support azure imds

Cargo.toml
* feat: Add debug log if cos web_identity is misconfigured by @godruoyi in https://github.com/Xuanwo/reqsign/pull/340
* fix: test aws signer with web loader by @everpcpc in https://github.com/Xuanwo/reqsign/pull/342
* fix: test for aws web loader by @everpcpc in https://github.com/Xuanwo/reqsign/pull/344
* fix(hash): let base64_decode return result by @oowl in https://github.com/Xuanwo/reqsign/pull/347
* ci: fix secret change for web loader test by @everpcpc in https://github.com/Xuanwo/reqsign/pull/348
* chore: Add settings for rust-analyzer by @Xuanwo in https://github.com/Xuanwo/reqsign/pull/349
* feat(services/aws): Add AssumeRoleLoader support by @Xuanwo in https://github.com/Xuanwo/reqsign/pull/356
* fix: update examples in docs by @messense in …
=> Bump to version 0.14

Cargo.toml
* `rust-ini` 0.20 bumped `ordered-multimap` to 0.7
* `ordered-multimap 0.71` fixed a feature renaming https://github.com/sgodwincs/ordered-multimap-rs/commit/131ab56bbc8e9e4d6df4b7e02c544407c675bc16
* The feature renaming is required for downstream application to bump nightly rust-toolchain. see https://github.com/rust-lang/rust/pull/114656
Please release a minor or patch version (both are OK because the update only breaks nightly toolchain and affect nothing on stable toolchain) after the PR got merged.
=> chore(deps): Bump rust-ini to 0.20

Cargo.toml
So we can get a link from https://crates.io/crates/reqsign to github.
@Xuanwo
=> Add repository field in cargo metadata

src/aws/config.rs, src/aws/constants.rs, src/aws/credential.rs
xref #202 
See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
Most AWS SDK supports it, for example boto3:
https://github.com/boto/botocore/blob/01dabf4d3dd645dcd921939a057429f0647cd2ec/botocore/utils.py#L396
=> feat: Add support for `AWS_EC2_METADATA_DISABLED` env var

src/azure/storage/sas/account_sas.rs, src/google/credential.rs, src/google/credential/external_account.rs, src/google/credential/impersonated_service_account.rs, src/google/token.rs, src/google/token/impersonated_service_account.rs, testdata/services/google/test_impersonated_service_account.json
The function names/variable names/error messages inside the `TokenLoader` impl might be wrong. I'm not really sure of all the terminology! Please let me know if I can improve them.
I'm also not super experienced with rust, so please let me know if anything is non-idiomatic as well, and I'll try and improve it.
I tested this branch by building OpenDAL against it, and I was able to successfully read a file from a bucket with an impersonated service account.
x-ref: #402
=> Google: Add support for impersonated service accounts

src/azure/constants.rs, src/azure/storage/signer.rs, src/ctx.rs
close https://github.com/Xuanwo/reqsign/issues/408
=> fix: azure storage signing failed for query contains `=`

src/google/credential.rs
- fix typo and bad grammar in `"credentail must be exist"`
- convert some `.unwrap()`s to `.expect()`s with nice error messages
=> Improve error messages in the tests for the various google account types

Cargo.toml, benches/aws.rs, src/aliyun/credential.rs, src/aliyun/oss.rs, src/aws/credential.rs, src/aws/v4.rs, src/azure/storage/sas/account_sas.rs, src/azure/storage/signer.rs, src/google/token.rs, src/huaweicloud/obs/signer.rs, src/oracle/credential.rs, src/tencent/cos.rs, src/tencent/credential.rs
This PR bumps reqwest (and by extension the rest of the hyper / http ecosustem to 1.0).
Note that I have also moved construction of the request out of the signing benchmark since the new API requires that we convert all the headers to strings which impacts the results. So now the bench is only the actual signing itself plus a clone of the processed headers.
=> deps: bump reqwest, chrone, rust-ini

Cargo.toml
reqwest is part of our public API, so we bump major version this time.
=> Bump to version 0.15.0

src/azure/storage/config.rs, src/azure/storage/workload_identity_credential.rs
=> fix(azure): load workload identity token from token file

.github/workflows/ci.yml
The macos-11 label has been deprecated and will no longer be available after 28 June 2024.
=> ci: migrate to macos-12

src/aws/config.rs, src/aws/credential.rs
Changes Done 
Adds support for configuring session duration while assume role. Defaults to 3600 seconds 
Fixes https://github.com/Xuanwo/reqsign/issues/465
=> AWS S3: Add support for assume role duration seconds

src/aliyun/oss.rs, src/aws/v4.rs, src/azure/storage/mod.rs, src/azure/storage/signer.rs, src/google/signer.rs, src/huaweicloud/obs/signer.rs, src/oracle/oci.rs, src/tencent/cos.rs
Small typo I noticed whilst browsing around. 
I first noticed it on the `google` service and checked elsewhere with `rg "Singer"` to find the rest.
=> docs: correct signer term usage

services/aws-v4/src/config.rs, services/aws-v4/src/constants.rs
The PR only add parsing support, however, it doesn't break anything so I think it's good enough.
It's a bit troublesome to verify whether this environment variable will affect the behavior of AWS STS, so we can check it later.
BTW, it's better to create a separate crate specifically for loading AWS profiles. This way, adding fields that reqsign might not be concerned with won't cause any issues.
=> feat: parse endpoint_url from profile and env

services/aws-v4/Cargo.toml, services/azure-storage/Cargo.toml, services/huaweicloud-obs/Cargo.toml
reqwest is not required in aws, azure and huawei cloud. Remove it to make dependencies neat.
=> chore: remove useless `reqwest` requirement

.github/workflows/release.yml
- Replace individual `cargo publish -p <crate>` steps with a single `cargo publish --workspace`
- Requires Rust 1.90.0 or newer
References:
- [Rust 1.90.0 release notes: Cargo adds native support for workspace publishing](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/#cargo-adds-native-support-for-workspace-publishing)
=> ci: use `cargo publish --workspace` for publishing all crates
